<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Shopware\Administration\Administration::class => ['all' => true],
    Shopware\Storefront\Storefront::class => ['all' => true],
    Shopware\Storefront\Framework\Framework::class => ['all' => true],
    Shopware\Storefront\Product\Product::class => ['all' => true],
    Shopware\Storefront\Account\Account::class => ['all' => true],
    Shopware\Storefront\Search\Search::class => ['all' => true],
    Shopware\Storefront\Framework\Seo\Seo::class => ['all' => true],
    Shopware\Storefront\Content\Content::class => ['all' => true],
    Shopware\Storefront\Checkout\Checkout::class => ['all' => true],
    Shopware\Storefront\Listing\Listing::class => ['all' => true],
    Shopware\Core\Framework\Framework::class => ['all' => true],
    Shopware\Core\System\System::class => ['all' => true],
    Shopware\Core\Content\Content::class => ['all' => true],
    Shopware\Core\Checkout\Checkout::class => ['all' => true],
];
