<?php

return [
    'swag-docs-administration-new-field' => 'AdministrationNewField',
    'swag-docs-api-controller' => 'ApiController',
    'swag-docs-base-class' => 'BaseClass',
    'swag-docs-custom-entity' => 'CustomEntity',
    'swag-docs-custom-entity-translations' => 'CustomEntityTranslations',
    'swag-docs-custom-service' => 'CustomService',
    'swag-docs-entity-extension' => 'EntityExtension',
    'swag-docs-payment-plugin' => 'PaymentPlugin',
    'swag-docs-plugin-commands' => 'PluginCommands',
    'swag-docs-plugin-config' => 'PluginConfig',
    'swag-docs-plugin-dependency' => 'PluginDependency',
    'swag-docs-plugin-migration-example' => 'PluginMigrationExample',
    'swag-docs-plugin-quick-start' => 'PluginQuickStart',
    'swag-docs-plugin-testing' => 'PluginTesting',
    'swag-docs-scheduled-task-plugin' => 'ScheduledTaskPlugin',
    'swag-docs-service-decoration' => 'ServiceDecoration',
    'swag-docs-storefront-api-controller' => 'StorefrontApiController',
    'swag-docs-subscriber-plugin' => 'SubscriberPlugin',
    'swag-docs-new-tab' => 'NewTab',
    'swag-docs-custom-component' => 'CustomComponent',
    'swag-docs-custom-module' => 'CustomModule',
    'swag-docs-custom-rule' => 'CustomRule',
    'swag-docs-extending-block' => 'ExtendingBlock',
    'swag-docs-administration-new-column' => 'AdministrationNewColumn',
    'swag-docs-cart-add-discount' => 'CartAddDiscountForProduct',
    'swag-docs-cart-change-price' => 'CartChangePrice',
    'swag-docs-rest-api-handling' => 'RestApiHandling',
    'swag-docs-custom-cms-element' => 'CustomCmsElement',
    'swag-docs-bundle-example' => 'BundleExample',
    'swag-docs-custom-cms-block' => 'CustomCmsBlock',
    'swag-docs-reading-plugin-config' => 'ReadingPluginConfig',
    'swag-docs-storefront-assets' => 'StorefrontAssets',
    'swag-docs-plugin-cypress-tests' => 'CypressTests',
    'swag-docs-extending-shopware-migration-profile' => 'ExtendingMigrationProfile',
    'swag-docs-extending-shopware-migration-connector' => 'MigrationConnector',
    'swag-docs-decorate-shopware-migration-converter' => 'MigrationConverter',
    'swag-docs-js-plugin' => 'JsPlugin',
    'swag-docs-extend-js-plugin' => 'ExtendJsPlugin',
    'swag-docs-storefront-controller' => 'StorefrontController',
    'swag-docs-create-migration-profile' => 'MigrationProfile',

];
